---

- name: Print deprecation notice
  pause:
    prompt: |
      ""
      "*** NOTE: This role is deprecated. ***"
      ""
      "Role sap_general_preconfigure provides all the features of this role, and more."
      "You can find the role in repository https://www.github.com/sap-linuxlab/community.sap_install ."
      ""
      "Press RETURN to continue anyway, or <ctrl>c, a, to abort:"

#- name: include os specific vars
  #include_vars: '{{ item }}'
  #with_first_found:
  #  - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
  #  - '{{ ansible_os_family }}.yml'
  #tags:
  #  - 'role::sap-base-settings'
  #  - 'role::sap-base-settings:install'
  #  - 'role::sap-base-settings:config'

- import_tasks: configuration.yml
  tags:
    - 'role::sap-base-settings'
    - 'role::sap-base-settings:config'
